kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: infra-dev
  namespace: infra-dev
subjects:
- kind: ServiceAccount
  name: ns-reconciler-infra-dev
  namespace: config-management-system
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io